---
- hosts: app
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
  - name: Import GPG key.
    rpm_key:
      key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"
      state: present

  - name: Install EPEL repo.
    yum: 
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm" 
      state: present

  - name: Install Remi repo.
    yum:
      name: "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
      state: present

  # - name: Check firewalld service status.
  #   shell: service firewalld status || true
  #   register: service_status_firewalld
  #   ignore_errors: yes

  # - name: Display service status.
  #   debug:
  #     msg: "firewalld service status: {{ service_status_firewalld.stdout }}"

  # - name: Ensure firewalld is stopped (since this is for testing).
  #   service: name=firewalld state=stopped

  - name: Install Node.js and npm.
    yum: name=npm state=present enablerepo=epel
  
  - name: Install Forever (to run our Node.js app).
    npm: name=forever global=yes state=present

  - name: Ensure Node.js app folder exists.
    file: "path={{ node_apps_location }} state=directory"

  - name: Copy example Node.js app to server.
    copy: "src=app dest={{ node_apps_location }}"

  - name: Install app dependencies defined in package.json.
    npm: path={{ node_apps_location }}/app

  - name: Check list of running Node.js apps.
    command: /usr/local/bin/forever list
    register: forever_list
    changed_when: false

  - name: Start example Node.js app.
    command: "/usr/local/bin/forever start {{ node_apps_location }}/app/app.js"
    when: "forever_list.stdout.find(node_apps_location + '/app/app.js') == -1"